### ISSUE TITLE
Minor additions/corrections for PCBWAY assembly

### ISSUE THREAD

**Issue by taintedkernel** [jakkra/ZSWatch-HW#11]
Hello, I received 2 more questions from PCBWAY regarding assembly and wanted to drop a note here.

First, the BOM has a component marked as R10 listed, but I do not see it on the schematic or PCB - so I'm guessing it was from a previous revision. I told PCBWAY to skip this, let me know if that is incorrect.

And second, a few of the ICs did not have pin 1 marked so they asked me. I looked at the PCB and highlighted the correct pin from what I saw. Attaching a image they provided with my highlights; it looks to be ICs 9 12 14 and 15.

![T-V9W519942A-微信截图_20231229164112](https://github.com/jakkra/ZSWatch-HW/assets/352735/e6168f2f-acc6-43bc-b2f6-cf9d6a3cfc3a)

**Comment by Kampi** [comment]
Hi @taintedkernel,

you should also miss `R6` in your BOM. The designators are wrong and `R10` is `R6`. Thanks for the correction. 

You can see the pin 1 markings in `Ref_Top.pdf` in the `docs` folder.

![image](https://github.com/jakkra/ZSWatch-HW/assets/3458587/196b65df-f713-4c1f-86b9-7c184ceaf541)

**Comment by taintedkernel** [comment]
Thank you @Kampi - they have not noticed this yet, but I will point it out.

They also pointed out for S1-S4 there is no solder mask opening for holes on top side and holes are covered with solder ink - they are asking if the holes are ok without opening pads on top, it can be reworked by them.  But if pads are necessary they would need a new order.

From what I see on the datasheet, they look to be through-hole and simply mechanical & not electrically connected, so I don't think pads would be necessary on the top?

![T-V9W519942A-1](https://github.com/jakkra/ZSWatch-HW/assets/352735/3a1ae05f-e8b5-4a96-b3e2-a5a2cfd736dd)
![T-V9W519942A](https://github.com/jakkra/ZSWatch-HW/assets/352735/1330b333-131a-4028-849b-0244d05f4688)

**Comment by Kampi** [comment]
Hi @taintedkernel,

you are right. The holes are only for mechanical stability. You can decide if you want a rework or not. I will adjust it in the footprint.

Btw. this is the first time I heard about this error. @jakkra do you had this issue already?

**Comment by jakkra** [comment]
@taintedkernel @Kampi I have done 3 orders without any issue, they never noticed this. You can go ahead, for me pcbway have probably soldered manually the bottons through holes afterwards.

**Comment by taintedkernel** [comment]
So I've heard back and they are saying the cause was due to a lack of a solder mask opening on the top side. The factory claims the holes are too small to rework and they suggest updating the design, then placing a new order.

Am I missing something? I used the files that are currently in the repo labeled 20231029 and it looks like there is an opening. At this point it's getting very frustrating dealing with PCBWAY and all of these problems.

**Comment by Kampi** [comment]
@taintedkernel I´m sorry for this trouble. As @jakkra mentioned we hadn´t had this problem so far and we ordered ~20 or more PCBs there. I checked an empty PCB on my desk and it looks good and there is no soldermask on the holes.

![image](https://github.com/jakkra/ZSWatch-HW/assets/3458587/c452eab3-c9e7-49d1-afeb-af31db8d04b5)

From my point of view, we have the following options:

- They try to assemble the push buttons and remove the pin for the hole. This might cause some more pressure on the pads
- They ship the buttons unsoldered and you try it on your own
- You have to order new PCBs and I have to check how we can avoid this

What is your preferred way to go? You can also forward your e-mail conversation to me (kontakt@daniel-kampert.de) and I can try to talk with them to find a solution.

**Comment by taintedkernel** [comment]
@Kampi I very much appreciate your (and @jakkra's) help on this and my frustration is definitely at PCBWAY!

From what I understand, it seems they have made an error somewhere in the manufacturing since your PCB doesn't have this issue and they were generated from the same source files.  I'm not sure I trust their job enough now for me to be able to fix whatever the issue is.

Assuming this is correct, I'd prefer them to fix their mistake and make a new set of PCBs.  Thank you for offering to jump into the conversation - I will go ahead with this route.

**Comment by Kampi** [comment]
@taintedkernel I´m not sure if it´s 100% an issue of PCBWay alone. I´ve figured out that the pad of the switch has no solder mask on the bottom (masked out), but the hole has solder mask (not masked out). It looks like the solder mask goes into the via. I adjusted the footprint to fix this issue now. The question is why hasn´t it happened in the previous orders. Maybe they changed the mask or the process. A good indicator for this is this marked via.

![image](https://github.com/jakkra/ZSWatch-HW/assets/3458587/39c69c9b-5ca8-4c87-a941-3db82f094cd2)

Here you can see that this via is covered by a bit solder mask, but not total. So it looks like the process isn´t very clean because otherwise all holes must be covered in the same way ("wrong" data -> same result on every location). But we have different results.

We can try to argue in this way with PCBWay and see what happens.
