### ISSUE TITLE
3D file

### ISSUE THREAD

**Issue by DREAM669** [jakkra/ZSWatch-HW#29]
Hi,@jakkra 
I have found button.inner.stl and button.inner.angled.stl in your CAD file. May I ask if there is any difference between these two?

**Comment by WenchongWang** [comment]
这是来自QQ邮箱的假期自动回复邮件。邮件已经收到，我会尽快回复您。

**Comment by jakkra** [comment]
Here it's marked which ones are the angles ones https://github.com/jakkra/ZSWatch/wiki/Case,-3D-printing-and-assembling#buttons

**Comment by DREAM669** [comment]
Okay, I understand. Is there any difference between these two sizes?

**Comment by jakkra** [comment]
@DREAM669 Yes you need two of each and they need to sit at the location specified in this image:
![image](https://github.com/jakkra/ZSWatch-HW/assets/4318648/af5f6c8f-612c-4d8b-a6c3-c6c1a5c327f9)

**Comment by DREAM669** [comment]
@jakkra ,Hi,Can you use a vernier caliper to measure the thickness of the battery and let me know?

**Comment by jakkra** [comment]
> @jakkra ,Hi,Can you use a vernier caliper to measure the thickness of the battery and let me know?

3.7mm

**Comment by DREAM669** [comment]
Hi,@jakkra 
May I ask what material is used for 3D printed watches on your end? What kind of glue is used to stick the buttons? I'm worried that paying taxes may not be able to stick it firmly. Thank you for your reply!

**Comment by jakkra** [comment]
> Hi,@jakkra May I ask what material is used for 3D printed watches ? What kind of glue is used to stick the buttons? I'm worried that paying taxes may not be able to stick it firmly. Thank you for your reply!

I have used PLA. For the buttons the outer cap is optional, so you can skip gluing it alos. But for those I use super glue, for example: https://www.loctiteproducts.com/en/products/fix/super-glue/loctite_super_gluelongneckbottle.html

**Comment by DREAM669** [comment]
Do you mean to use the one inside directly? Will it not move without an outer cover, and even fall into the watch?
