### ISSUE TITLE
Please fill in total quantity of single PCBs

### ISSUE THREAD

**Issue by HUGOW04** [jakkra/ZSWatch-HW#3]
![image](https://github.com/jakkra/ZSWatch-HW/assets/54809176/a66c4a82-7a41-42f4-a6ad-5717ae1112af)

**Comment by HUGOW04** [comment]
I can also not upload 4 files just one on the upload .png 
![image](https://github.com/jakkra/ZSWatch-HW/assets/54809176/385e0e61-0b6e-43df-a896-57bd75873794)

**Comment by jakkra** [comment]
Hi @HUGOW04 the quantity is the amount of PCBs you want PCBWay to assemble, you fill that in.

You can add more files when you have it on the Cart also. I ordered just 2 weeks ago and could upload all necessary files.
![image](https://github.com/jakkra/ZSWatch-HW/assets/4318648/97e84abf-1a36-4420-8211-d82e494b30f8)

**Comment by jakkra** [comment]
The above looks correct, there will always be an audit from pcbway for assembly, you will get a quoted BOM from them with the price for components.

**Comment by HUGOW04** [comment]
oh thanks I see but do I need to buy some special display and what bettery and display do you recommend??

**Comment by jakkra** [comment]
Yes, here:
https://www.buydisplay.com/240x240-round-ips-tft-lcd-display-1-28-capacitive-touch-circle-screen
https://www.aliexpress.com/item/4000121983257.html?spm=a2g0o.order_list.order_list_main.5.4b3418027XxHjE
