### ISSUE TITLE
holes for the motor

### ISSUE THREAD

**Issue by DREAM669** [jakkra/ZSWatch-HW#32]
@jakkra ,Hello, is it necessary to leave holes for the motor on the PCB board?
If the wire passes through the back of the hole without leaving any space for the wire, right?

**Comment by jakkra** [comment]
Not sure what you mean, have you looked here https://github.com/jakkra/ZSWatch/wiki/Case,-3D-printing-and-assembling#preparing-the-pcb

**Comment by DREAM669** [comment]
@jakkra ，I would like to ask you what is the difference between inner_holder_support and inner_holder_no_support?
