### ISSUE TITLE
Testing V2.0.5

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch-HW#36]
- [x] USB with new dock
- [x] SWD with Dock rev 3
- [x] SWD with Dock <rev 3
- [x] Microphone
- [x] Speaker
- [x] nPM1300 power supply
- [x] nPM1300 system reset
- [x] Flash memory
- [x] Bridge to disable USB Switch IC

**Comment by Kampi** [comment]
Regular 64 Flash memory doesn't work because wrong component with wrong sector size. A 32 MB Flash with the right sector size is working. 64 MB will be testet next.

**Comment by jakkra** [comment]
Buzzer OK

**Comment by jakkra** [comment]
nPM System Reset OK

**Comment by jakkra** [comment]
Done all working
