### ISSUE TITLE
Remove jumper from BOM and match Layer names in gerbers with KiCad

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch-HW#46]
![image (5)](https://github.com/jakkra/ZSWatch-HW/assets/4318648/9acdba62-97c4-4c45-9d75-e8af33fa4ff2)

Different names
![image](https://github.com/jakkra/ZSWatch-HW/assets/4318648/08da0a30-597f-4255-a180-75bb5ca54af5)

**Comment by Kampi** [comment]
Are you speaking about the innter layers? The rest looks imo okay

**Comment by Kampi** [comment]
@jakkra please check it

**Comment by jakkra** [comment]
> @jakkra please check it

Layers still have different names, exported gerbers say "ZSWatch-F_Cu.gbr"

BOM is OK

**Comment by Kampi** [comment]
@jakkra I prefer the project name in the Gerber files to identify them easily in case I have to check them manually. So I would leave the prefix as it is.

**Comment by jakkra** [comment]
Great
