### ISSUE TITLE
Generated render of PCB wrong after library changes

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch-HW#88]
Components missing. Ci needs update.
![image](https://github.com/user-attachments/assets/ba1776c0-22a8-4d9c-97dd-eb8bbb192f9f)

Guess something needs to be updated here https://github.com/jakkra/ZSWatch-HW/blob/main/project/zswatch.kibot.yaml

**Comment by Kampi** [comment]
The issue is fixed in [here](https://github.com/Kampi/ZSWatch-HW/tree/2.0.6_Dev)

**Comment by Kampi** [comment]
Fixed in [2.0.6_Dev](https://github.com/Kampi/ZSWatch-HW/tree/2.0.6_Dev)

https://github.com/Kampi/ZSWatch-HW/actions/runs/11730072439

**Comment by Kampi** [comment]
Fixed in 2.0.6_Dev
