### ISSUE TITLE
1.8-3.3V level shift

### ISSUE THREAD

**Issue by DREAM669** [jakkra/ZSWatch-HW#9]
Hello, I have noticed that the chip you are using for the 1.8V-3.3V level shift is TXB0104QRUTRQ1, but you are currently using NTS0104GU12. May I know the reason? Is there any defect in TXB0104?Thanks!

**Comment by Kampi** [comment]
Hi @DREAM669,

can you explain it further? We are using `NTS0104GU12` in both the schematics and the BOM (at least for rev 3). In theory, both versions should work. The `TXB0104QRUTRQ1` supports a higher voltage range and costs a little bit more.

**Comment by DREAM669** [comment]
Hello, I think so. The first version of the schematic used the TXB0104 module, but the later version was changed to NTS0104. Is TXB0104 unable to adapt to Touch functionality?

**Comment by jakkra** [comment]
> Hello, I think so. The first version of the schematic used the TXB0104 module, but the later version was changed to NTS0104. Is TXB0104 unable to adapt to Touch functionality?

Yes if I remember correctly it was touch not working because that logic shifter didn't work well for i2c.

**Comment by Kampi** [comment]
Hi @DREAM669 

does it answer your question and can we close this ticket?

**Comment by DREAM669** [comment]
Of course, my problem has been resolved. Thank you.
